#!/usr/bin/env node
const fs = require("fs")
const meow = require("meow")
const mime = require("mime-types")
const validate = require(__dirname)

const cli = meow(`
    Usage
        $ validate-it <path> <path>...
`)

/**
 * Entry point for validate-it
 * @returns {number} Exit status for validate-it.
 */
async function main() {
    const results = await Promise.all(cli.input.map(async function(path) {
        const fullType = mime.lookup(path)
        if(!fullType) {
            console.error(`File ${path} is of invalid or unknown type!`)
            return 2
        }

        let valid
        try {
            const text = fs.readFileSync(path, {encoding: "utf-8"})
            valid = await validate(text, fullType)
        }
        catch(e) {
            console.error(e.message)
            return 2
        }

        if(valid) {
            console.log(`File ${path} is valid!`)
            return 0
        }
        console.error(`File ${path} is not valid!`)
        return 1
    }))

    let result = 0
    if(results.includes(2)) {
        result = 2
    }
    else if(results.includes(1)) {
        result = 1
    }
    process.exit(result)
}

main()
